### ISSUE TITLE
Single Core 100% load on xfce

### ISSUE THREAD

**Issue by Cyspy** [vinceliuice/vimix-gtk-themes#56] opened 2018-01-27 12:55 UTC
I'm using xfce4 with the compiz 0.9 as default wm on my archlinux running on an Lenovo laptop (4720HQ, HD4600). The vimix theme coms from AUR. I'm facing 100% CPU usage on single core, which is 12% of my full CPU. The process that uses these CPU is 
```
/usr/bin/X :0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch -background none
```
as shown in htop.

And yes, this also happen on xfwm4. so it's not about compiz.

I've found some similar sound on, like, AskUbuntu. but I cant confirm if it is also the same problem.

**Comment by vinceliuice** [comment] 2018-01-27 17:43
You can download Vimix from github and try again, I test on my xfce4, but I don't have this issue. CPU works well.

**Comment by siick** [comment] 2018-01-30 07:56
Ok i'ill try to get the last version from github and test because i'm facing exactly the issue on my Debian 9 with XFCE.

**Comment by vinceliuice** [comment] 2018-01-31 09:19
Does it always or just temporary, When I switch to Vimix my CPU is also used very high but just temporary, After a while, it will clam down.

**Comment by vinceliuice** [comment] 2018-01-31 09:22
I don't know why but I will go see materia-theme to check if it also has this problem, because my theme based on materia-theme, Maybe is because it used many Animation effects

**Comment by siick** [comment] 2018-02-03 10:34
@vinceliuice Yes, it is not temporary. The CPU charge never go down :/

**Comment by siick** [comment] 2018-02-03 10:42
@vinceliuice I have installed your theme on my laptop with Ubuntu 16.04 and XFCE and i don't have the problem. So it is just on my Debian 9.

**Comment by vinceliuice** [comment] 2018-02-05 04:02
@siick That's very weird, I am confused, and I have no solution to this for now, sorry about this!

**Comment by coreybruce** [comment] 2018-04-05 09:52
I have high cpu issues when using any form of materia-themes in Xubuntu 16.04 LTS

**Comment by AnthonyDiGirolamo** [comment] 2018-04-06 16:51
Using XFCE 4.12 on DebianTesting I am also getting 100% CPU usage from Xorg.

Changing the panel appearance background style from "None (use system style)" to "Solid color" fixes it. I haven't tested this on the [materia-theme](https://github.com/nana-4/materia-theme/issues/177) but suspect it may fix the issue there as well.

**Comment by dhqvinh** [comment] 2018-05-14 08:05
Thanks @AnthonyDiGirolamo.
I'm using 4.16.8-1-ARCH, had the same issue "100% CPU usage from Xorg" and it's been fixed after trying your solution.

**Comment by gsantner** [comment] 2018-08-22 14:57
Confirming that this "fix"/workaround works.

**Comment by jeanlandim** [comment] 2018-09-21 01:23
thanks @AnthonyDiGirolamo

**Comment by pfuender** [comment] 2018-10-12 08:53
I've been having this exact same issue, but it looks like, one of the recent commits fixed the high cpu load. Thanks a lot!

**Comment by vinceliuice** [comment] 2018-10-12 09:51
I removed some extra animation effects and transitions, so maybe this fixed it, Since the problem is solved, then I will close the issue

**Closed by vinceliuice** 2018-10-12 09:51 UTC

**Comment by Souravgoswami** [comment] 2019-02-15 03:11
Hi @vinceliuice, I have modded your theme, which is called XFCE Colour Lite, but I am unable to figure out why the CPU goes to 100% (the most CPU is used by panel and Xorg) when I enable 'None (use system style)' from the xfce4 panel menu.

**Comment by Souravgoswami** [comment] 2019-02-15 08:09
Looks like removing these lines fixes the problem:


 transition: all 0.3s cubic-bezier(0, 0, 0.2, 1), box-shadow 0.2s cubic-bezier(0, 0, 0.2, 1);
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.2);
  background-color: #FAFAFA;
  background-image: radial-gradient(circle farthest-corner at center, alpha(currentColor, 0) 100%, transparent 0%), image(alpha(currentColor, 0));



.inline-toolbar button:not(.text-button), modelbutton.flat,
.menuitem.button.flat, spinbutton:not(.vertical) button, spinbutton.vertical button, notebook > header > tabs > arrow, scrollbar button, check,
radio, calendar.button, messagedialog.csd .dialog-action-area button, button.sidebar-button, .gedit-search-slider button, PanelToplevel > widget > button, .budgie-settings-window buttonbox.inline-toolbar button, .raven .raven-header:not(.top) button, .drop-shadow button, .budgie-session-dialog .linked.horizontal > button, .lightdm-gtk-greeter button, :not(headerbar) .caja-pathbar button, .caja-pathbar :not(headerbar) button, :not(headerbar) .path-bar button, layouttabbar button, .mate-panel-menu-bar #PanelApplet button:not(.flat), .raven stackswitcher.linked > button, toolbar button, actionbar > revealer > box button:not(.suggested-action):not(.destructive-action):not(.server-list-button), .app-notification button,
button.flat {
  transition: all 0.3s cubic-bezier(0, 0, 0.2, 1);
  box-shadow: none;
  background-color: transparent;
  background-image: radial-gradient(circle farthest-corner at center, alpha(currentColor, 0) 100%, transparent 0%), image(alpha(currentColor, 0));
  color: alpha(currentColor, 0.75);
}

**Comment by vinceliuice** [comment] 2019-02-17 10:22
Well, thanks, I'll fix it according to this

**Comment by Souravgoswami** [comment] 2019-02-17 11:06
Thanks, but you can reproduce it with (I am using Arch, the package names may vary on other distributions):

1. You need xfce4-panel first.
2. You go to Panel Preferences, and use Style: Solid Colour under Appearance.
3. Install xfce4-whiskermenu-plugin.
4. Under the Panel Preferences, add Whisker Menu.

And you will see the problem. This could be the whiskermenu plugin bug. I am not sure. Changing the button layout on your theme could make it look a bit more dull, see if you can work around that!

Thank you.

**Comment by vinceliuice** [comment] 2019-02-17 13:26
You can use the last version of vimix, I find out I've fixed this issue at previous version
